/**
 * The product's name and the brand files every page and the admin point at.
 *
 * One module rather than literals in the locale layout and in
 * `payload.config.ts`, because both declare the same favicon and share image
 * and `app/(frontend)/[locale]/layout.test.ts` checks every path named here
 * against `public/` without rendering either of them.
 *
 * The files themselves are generated by `packages/brand` and committed; nothing
 * here or in the build produces them.
 */

/** The product's name, wherever it names the product rather than the method. */
export const SITE_NAME = "SMOG & Co";

/** `tokens.color.brand.primary` in `@smog/styles`, and the manifest's `theme_color`. */
export const BRAND_PRIMARY = "#00805F";

/**
 * The dark theme's page background, `--color-background` under `.dark` in
 * `@smog/ui-web/styles/theme.css`.
 *
 * A literal because `apps/site` does not depend on `@smog/styles`, and
 * `app/(frontend)/[locale]/layout.test.ts` reads the stylesheet to hold the
 * two together.
 */
export const DARK_BACKGROUND = "#0E1013";

interface IconLink {
  sizes?: string;
  type?: string;
  url: string;
}

/**
 * The favicons, in the shape Next's `metadata.icons` and Payload's
 * `admin.meta.icons` both accept.
 *
 * `sizes="32x32"` on the ICO, not `"any"`: Chromium picks an `"any"` ICO over
 * the SVG beside it, and the SVG is the sharper of the two at every size. The
 * ICO still carries 16, 32 and 48 px frames for the browsers that take it.
 */
export const FAVICONS: IconLink[] = [
  { sizes: "32x32", url: "/favicon.ico" },
  { type: "image/svg+xml", url: "/icon.svg" },
];

/** iOS ignores `rel="icon"` for the home screen and asks for this instead. */
export const APPLE_TOUCH_ICON: IconLink = {
  sizes: "180x180",
  url: "/apple-touch-icon.png",
};

/** A static file in `public/`, served before the Worker runs. */
export const MANIFEST_PATH = "/manifest.webmanifest";

/**
 * The link-preview image: the white logo on the brand green, at the 1200×630
 * that Open Graph consumers and X's large card are designed around.
 */
export const SHARE_IMAGE = {
  alt: SITE_NAME,
  height: 630,
  url: "/og.png",
  width: 1200,
};
