import { expect, test } from "@playwright/test";
import {
  cleanupGestureDetailFixtures,
  type GestureDetailFixtures,
  seedGestureDetailFixtures,
} from "../helpers/seedGestureDetail";

const SITE = "http://localhost:3003";

/**
 * `/robots.txt` and `/sitemap.xml`, fetched the way a crawler fetches them.
 *
 * This is the only test that exercises the whole path. Both files are
 * generated by Payload endpoints (`src/endpoints/crawler.ts`) and reached
 * through rewrites in `next.config.ts`, because a Next metadata route that
 * imports Payload costs ~520 KiB of Worker bundle — and that indirection has
 * two ways to fail silently that no unit test can see: the rewrite can stop
 * matching, and `handleEndpoints` can stop matching the path. Next 16 already
 * demonstrated the class of failure once already, by ignoring a
 * `robots.ts` placed inside a route group without a word of warning.
 *
 * `request` rather than `page`: these are files, not documents, and a browser
 * would only add a parser between the assertion and the bytes.
 */
test.describe("Crawler files", () => {
  let fixtures: GestureDetailFixtures;

  test.beforeAll(async () => {
    fixtures = await seedGestureDetailFixtures();
  });

  test.afterAll(async () => {
    await cleanupGestureDetailFixtures(fixtures);
  });

  test("serves robots.txt at the conventional URL", async ({ request }) => {
    const response = await request.get(`${SITE}/robots.txt`);

    expect(response.status()).toBe(200);
    expect(response.headers()["content-type"]).toContain("text/plain");

    const body = await response.text();

    expect(body).toContain("User-Agent: *");
    expect(body).toContain("Disallow: /nl/favorites");
    // Absolute, and on the host the request arrived at.
    expect(body).toContain(`Sitemap: ${SITE}/sitemap.xml`);
  });

  test("serves sitemap.xml at the conventional URL", async ({ request }) => {
    const response = await request.get(`${SITE}/sitemap.xml`);

    expect(response.status()).toBe(200);
    expect(response.headers()["content-type"]).toContain("application/xml");

    const body = await response.text();

    expect(body).toContain(
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"'
    );
    expect(body).toContain(`<loc>${SITE}/nl/gestures</loc>`);
  });

  test("lists an active gesture in all three locales", async ({ request }) => {
    const body = await (await request.get(`${SITE}/sitemap.xml`)).text();

    for (const locale of ["nl", "en", "fr"]) {
      expect(body).toContain(
        `<loc>${SITE}/${locale}/gestures/${fixtures.activeId}</loc>`
      );
    }
  });

  test("never lists an inactive gesture", async ({ request }) => {
    // The end-to-end half of `sitemap.int.test.ts`'s access assertion: the
    // response a crawler actually receives must not advertise a URL the site
    // answers 404 to.
    const body = await (await request.get(`${SITE}/sitemap.xml`)).text();

    expect(body).not.toContain(`/gestures/${fixtures.inactiveId}<`);
  });

  test("lists no favorites page, which robots.txt disallows", async ({
    request,
  }) => {
    const body = await (await request.get(`${SITE}/sitemap.xml`)).text();

    expect(body).not.toContain("favorites");
  });
});
