import { default as handler } from "./.open-next/worker.js";
import { type CronEnvironment, onScheduled } from "./src/jobs/cron";

/**
 * The Worker entry `wrangler.jsonc`'s `main` points at: OpenNext's generated
 * `fetch`, plus the hourly `scheduled()` that drains the job queue. The
 * pattern is OpenNext's own (https://opennext.js.org/cloudflare/howtos/custom-worker).
 * No Durable Object classes are re-exported because this app binds none; add
 * them here if `open-next.config.ts` ever enables the DO queue or tag cache.
 *
 * The tick is dispatched into this Worker's own `fetch`, in-process, so it
 * runs through the same middleware and Payload instance as any request.
 *
 * `./.open-next/worker.js` does not exist in a fresh checkout — it is
 * generated by `opennextjs-cloudflare build` — and `tsconfig.json` excludes
 * `.open-next` so a stale build's output is never typechecked. The import
 * above still needs a module for `moduleResolution: bundler` to resolve
 * against when nothing has been built; `open-next-worker.d.ts` supplies that
 * ambient declaration so this file typechecks in both states.
 *
 * `ExportedHandler<CloudflareEnv & CronEnvironment>` rather than plain
 * `CloudflareEnv`: `wrangler types` never emits `JOBS_RUN_TOKEN`, a secret,
 * so `env` needs `CronEnvironment` intersected in for `onScheduled` to type
 * check against something more than an empty overlap. See the doc comment on
 * `CronEnvironment` in `src/jobs/cron.ts`.
 */
export default {
  fetch: handler.fetch,
  scheduled(_controller, env, ctx) {
    onScheduled(env, ctx, (request) => handler.fetch(request, env, ctx));
  },
} satisfies ExportedHandler<CloudflareEnv & CronEnvironment>;
