import type { ReactNode } from "react";
import { themeInitScript } from "@/lib/theme";
import "../app/(frontend)/tailwind.css";

/**
 * The one component in this app that renders `<html>` and `<body>`.
 *
 * Next puts `<html>` in the root layout by convention, but the `lang`
 * attribute has to say which locale the page is in, and the root layout of
 * the `(frontend)` group sits *above* the `[locale]` segment — it has no
 * params and cannot know. So the document moves down to the layouts that do
 * know, and this component keeps the three of them from drifting: the
 * localized shell, the kitchen sink and the not-found page.
 *
 * Verified against `next@16.3.3` rather than assumed: the "missing `<html>`
 * and `<body>` tags in the root layout" check is
 * `createRootLayoutValidatorStream` in
 * `node_modules/next/dist/server/stream-utils/node-web-streams-helper.js`,
 * which inspects the *rendered stream*, not which module emitted the tags.
 * A root layout that passes its children straight through is therefore fine
 * as long as everything below it paints a document — which is what the three
 * callers here guarantee.
 */
export function SiteDocument({
  lang,
  children,
}: {
  lang: string;
  children: ReactNode;
}) {
  return (
    /*
     * `suppressHydrationWarning` because the script below writes to
     * `<html class>` before React hydrates, which React would otherwise
     * report as a mismatch on every load. It suppresses the warning for this
     * element's own attributes only, not for the tree beneath it.
     */
    <html lang={lang} suppressHydrationWarning>
      <head>
        {/*
         * The theme class has to be on `<html>` before the first paint, and
         * the earliest a React component can act is after hydration — one
         * painted frame too late, which a reader sees as a white flash on
         * every load of a page they are looking at in dark mode. A blocking
         * inline script is the only thing that runs early enough.
         */}
        <script
          // biome-ignore lint/security/noDangerouslySetInnerHtml: the content is generated by `themeInitScript()` from this repository's own constants — no request, no user and no database reaches it — and a `<script>` element takes its body no other way.
          dangerouslySetInnerHTML={{ __html: themeInitScript() }}
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
