/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GesturesRouteImport } from './routes/gestures'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GesturesIdRouteImport } from './routes/gestures.$id'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GesturesRoute = GesturesRouteImport.update({
  id: '/gestures',
  path: '/gestures',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GesturesIdRoute = GesturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GesturesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gestures': typeof GesturesRouteWithChildren
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/gestures/$id': typeof GesturesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gestures': typeof GesturesRouteWithChildren
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/gestures/$id': typeof GesturesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/gestures': typeof GesturesRouteWithChildren
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/gestures/$id': typeof GesturesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/gestures'
    | '/login'
    | '/success'
    | '/gestures/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/gestures' | '/login' | '/success' | '/gestures/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/gestures'
    | '/login'
    | '/success'
    | '/gestures/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GesturesRoute: typeof GesturesRouteWithChildren
  LoginRoute: typeof LoginRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestures': {
      id: '/gestures'
      path: '/gestures'
      fullPath: '/gestures'
      preLoaderRoute: typeof GesturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestures/$id': {
      id: '/gestures/$id'
      path: '/$id'
      fullPath: '/gestures/$id'
      preLoaderRoute: typeof GesturesIdRouteImport
      parentRoute: typeof GesturesRoute
    }
  }
}

interface GesturesRouteChildren {
  GesturesIdRoute: typeof GesturesIdRoute
}

const GesturesRouteChildren: GesturesRouteChildren = {
  GesturesIdRoute: GesturesIdRoute,
}

const GesturesRouteWithChildren = GesturesRoute._addFileChildren(
  GesturesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GesturesRoute: GesturesRouteWithChildren,
  LoginRoute: LoginRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
