/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GesturesRouteImport } from './routes/gestures'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GesturesIdRouteImport } from './routes/gestures_.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GesturesRoute = GesturesRouteImport.update({
  id: '/gestures',
  path: '/gestures',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GesturesIdRoute = GesturesIdRouteImport.update({
  id: '/gestures_/$id',
  path: '/gestures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/gestures': typeof GesturesRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gestures/$id': typeof GesturesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/gestures': typeof GesturesRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gestures/$id': typeof GesturesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/gestures': typeof GesturesRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gestures_/$id': typeof GesturesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/gestures'
    | '/login'
    | '/success'
    | '/auth/callback'
    | '/gestures/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/gestures'
    | '/login'
    | '/success'
    | '/auth/callback'
    | '/gestures/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/gestures'
    | '/login'
    | '/success'
    | '/auth/callback'
    | '/gestures_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
  GesturesRoute: typeof GesturesRoute
  LoginRoute: typeof LoginRoute
  SuccessRoute: typeof SuccessRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GesturesIdRoute: typeof GesturesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestures': {
      id: '/gestures'
      path: '/gestures'
      fullPath: '/gestures'
      preLoaderRoute: typeof GesturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestures_/$id': {
      id: '/gestures_/$id'
      path: '/gestures/$id'
      fullPath: '/gestures/$id'
      preLoaderRoute: typeof GesturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
  GesturesRoute: GesturesRoute,
  LoginRoute: LoginRoute,
  SuccessRoute: SuccessRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GesturesIdRoute: GesturesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
