/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GesturesRouteImport } from './routes/gestures'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SponsorsIndexRouteImport } from './routes/sponsors/index'
import { Route as SponsorsSuccessRouteImport } from './routes/sponsors/success'
import { Route as SponsorsCreateRouteImport } from './routes/sponsors/create'
import { Route as GesturesIdRouteImport } from './routes/gestures_.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GesturesRoute = GesturesRouteImport.update({
  id: '/gestures',
  path: '/gestures',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsIndexRoute = SponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsSuccessRoute = SponsorsSuccessRouteImport.update({
  id: '/sponsors/success',
  path: '/sponsors/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsCreateRoute = SponsorsCreateRouteImport.update({
  id: '/sponsors/create',
  path: '/sponsors/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GesturesIdRoute = GesturesIdRouteImport.update({
  id: '/gestures_/$id',
  path: '/gestures/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/gestures': typeof GesturesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gestures/$id': typeof GesturesIdRoute
  '/sponsors/create': typeof SponsorsCreateRoute
  '/sponsors/success': typeof SponsorsSuccessRoute
  '/sponsors': typeof SponsorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/gestures': typeof GesturesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gestures/$id': typeof GesturesIdRoute
  '/sponsors/create': typeof SponsorsCreateRoute
  '/sponsors/success': typeof SponsorsSuccessRoute
  '/sponsors': typeof SponsorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/gestures': typeof GesturesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gestures_/$id': typeof GesturesIdRoute
  '/sponsors/create': typeof SponsorsCreateRoute
  '/sponsors/success': typeof SponsorsSuccessRoute
  '/sponsors/': typeof SponsorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/gestures'
    | '/login'
    | '/privacy'
    | '/success'
    | '/terms'
    | '/auth/callback'
    | '/gestures/$id'
    | '/sponsors/create'
    | '/sponsors/success'
    | '/sponsors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/gestures'
    | '/login'
    | '/privacy'
    | '/success'
    | '/terms'
    | '/auth/callback'
    | '/gestures/$id'
    | '/sponsors/create'
    | '/sponsors/success'
    | '/sponsors'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/gestures'
    | '/login'
    | '/privacy'
    | '/success'
    | '/terms'
    | '/auth/callback'
    | '/gestures_/$id'
    | '/sponsors/create'
    | '/sponsors/success'
    | '/sponsors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
  GesturesRoute: typeof GesturesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SuccessRoute: typeof SuccessRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GesturesIdRoute: typeof GesturesIdRoute
  SponsorsCreateRoute: typeof SponsorsCreateRoute
  SponsorsSuccessRoute: typeof SponsorsSuccessRoute
  SponsorsIndexRoute: typeof SponsorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestures': {
      id: '/gestures'
      path: '/gestures'
      fullPath: '/gestures'
      preLoaderRoute: typeof GesturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/': {
      id: '/sponsors/'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/success': {
      id: '/sponsors/success'
      path: '/sponsors/success'
      fullPath: '/sponsors/success'
      preLoaderRoute: typeof SponsorsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/create': {
      id: '/sponsors/create'
      path: '/sponsors/create'
      fullPath: '/sponsors/create'
      preLoaderRoute: typeof SponsorsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestures_/$id': {
      id: '/gestures_/$id'
      path: '/gestures/$id'
      fullPath: '/gestures/$id'
      preLoaderRoute: typeof GesturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
  GesturesRoute: GesturesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SuccessRoute: SuccessRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GesturesIdRoute: GesturesIdRoute,
  SponsorsCreateRoute: SponsorsCreateRoute,
  SponsorsSuccessRoute: SponsorsSuccessRoute,
  SponsorsIndexRoute: SponsorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
