// @vitest-environment node
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { Metadata } from "next";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { BRAND_PRIMARY, DARK_BACKGROUND, SITE_NAME } from "@/lib/brand";
import { generateMetadata, viewport } from "./layout";

/*
 * The layout's metadata against the files it names.
 *
 * Every icon, the manifest and the share image are plain files in `public/`,
 * generated by `packages/brand` and committed. A path that drifts from its file
 * fails nowhere else: the page renders, the `<link>` is there, and the browser
 * quietly shows no favicon, or a link preview shows no image. So each path the
 * metadata or the manifest mentions is checked against the directory here.
 *
 * `next/headers` only resolves inside a request, and `readSession` would boot
 * Payload for a function this file never calls, so both are replaced.
 */
const requestHeaders = vi.hoisted(() => ({ current: new Headers() }));

vi.mock("next/headers", () => ({
  headers: async () => requestHeaders.current,
}));

vi.mock("@/lib/session", () => ({ readSession: vi.fn() }));

/** Vitest runs with the app directory as its cwd. */
const PUBLIC_DIR = join(process.cwd(), "public");

const THEME_CSS = join(
  process.cwd(),
  "../../packages/ui-web/src/styles/theme.css"
);

const publicFile = (url: string): string => join(PUBLIC_DIR, url);

/** Width and height from a PNG's IHDR chunk, which always starts at byte 16. */
const pngSize = (url: string): string => {
  const bytes = readFileSync(publicFile(url));

  return `${bytes.readUInt32BE(16)}x${bytes.readUInt32BE(20)}`;
};

const urlsOf = (entries: unknown): string[] => {
  if (entries === undefined) {
    return [];
  }

  return (Array.isArray(entries) ? entries : [entries]).map((entry) =>
    typeof entry === "string" ? entry : String((entry as { url: unknown }).url)
  );
};

/** Every path the resolved metadata points at, whatever key it sits under. */
const referencedPaths = (metadata: Metadata): string[] => {
  const icons = metadata.icons as { apple: unknown; icon: unknown };

  return [
    ...urlsOf(icons.icon),
    ...urlsOf(icons.apple),
    String(metadata.manifest),
    ...urlsOf(metadata.openGraph?.images),
    ...urlsOf(metadata.twitter?.images),
  ];
};

interface ManifestIcon {
  purpose?: string;
  sizes: string;
  src: string;
  type: string;
}

const readManifest = (): Record<string, unknown> & { icons: ManifestIcon[] } =>
  JSON.parse(readFileSync(publicFile("/manifest.webmanifest"), "utf8"));

/** A `--color-*` declaration from the `@theme` block or the `.dark` block. */
const themeColor = (block: "dark" | "light", name: string): string => {
  const css = readFileSync(THEME_CSS, "utf8");
  const start = block === "dark" ? css.indexOf(".dark {") : 0;
  const match = new RegExp(`--color-${name}:\\s*(#[0-9A-Fa-f]{6})`).exec(
    css.slice(start)
  );

  return match?.[1]?.toUpperCase() ?? "";
};

const metadataFor = (locale: string): Promise<Metadata> =>
  generateMetadata({ params: Promise.resolve({ locale }) });

describe("the locale layout's metadata", () => {
  beforeEach(() => {
    requestHeaders.current = new Headers({ host: "localhost:3003" });
  });

  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it("names the site SMOG & Co, and puts the name after every page title", async () => {
    const metadata = await metadataFor("nl");

    expect(metadata.title).toEqual({
      default: SITE_NAME,
      template: `%s — ${SITE_NAME}`,
    });
    expect(SITE_NAME).toBe("SMOG & Co");
  });

  it.each([
    "nl",
    "en",
    "fr",
  ])("points %s at files that exist in public/", async (locale) => {
    const paths = referencedPaths(await metadataFor(locale));

    expect(paths).toEqual(
      expect.arrayContaining([
        "/favicon.ico",
        "/icon.svg",
        "/apple-touch-icon.png",
        "/manifest.webmanifest",
        "/og.png",
      ])
    );
    for (const path of paths) {
      expect(existsSync(publicFile(path)), path).toBe(true);
    }
  });

  it("gives the not-found page of an unknown locale the icons too", async () => {
    const paths = referencedPaths(await metadataFor("de"));

    expect(paths).toContain("/favicon.ico");
    for (const path of paths) {
      expect(existsSync(publicFile(path)), path).toBe(true);
    }
  });

  it("declares the share image at the size of the file", async () => {
    const metadata = await metadataFor("nl");
    const [image] = metadata.openGraph?.images as {
      alt: string;
      height: number;
      url: string;
      width: number;
    }[];

    expect(image).toEqual({
      alt: "SMOG & Co",
      height: 630,
      url: "/og.png",
      width: 1200,
    });
    expect(pngSize("/og.png")).toBe("1200x630");
    expect(pngSize("/apple-touch-icon.png")).toBe("180x180");
    expect(metadata.twitter).toMatchObject({ card: "summary_large_image" });
  });

  it("resolves relative URLs against SITE_ORIGIN when the Worker has one", async () => {
    vi.stubEnv("SITE_ORIGIN", "https://smog.example");

    const metadata = await metadataFor("nl");

    expect(metadata.metadataBase?.toString()).toBe("https://smog.example/");
  });

  it("falls back to the request's own origin without SITE_ORIGIN", async () => {
    vi.stubEnv("SITE_ORIGIN", "");

    const metadata = await metadataFor("nl");

    expect(metadata.metadataBase?.toString()).toBe("http://localhost:3003/");
  });

  it("keeps og:title, og:description and alternates for the pages to fill", async () => {
    const metadata = await metadataFor("nl");

    expect(metadata.alternates).toBeUndefined();
    expect(metadata.openGraph).not.toHaveProperty("title");
    expect(metadata.openGraph).not.toHaveProperty("description");
  });

  it("colours the browser chrome green in light mode and the page background in dark", () => {
    expect(viewport.themeColor).toEqual([
      { color: "#00805F", media: "(prefers-color-scheme: light)" },
      { color: DARK_BACKGROUND, media: "(prefers-color-scheme: dark)" },
    ]);
    // The literals in `lib/brand.ts` against the stylesheet they copy.
    expect(BRAND_PRIMARY).toBe(themeColor("light", "primary"));
    expect(DARK_BACKGROUND).toBe(themeColor("dark", "background"));
  });
});

describe("manifest.webmanifest", () => {
  it("parses, and carries the fields an install prompt needs", () => {
    const manifest = readManifest();

    expect(manifest).toMatchObject({
      display: "standalone",
      name: "SMOG & Co",
      short_name: "SMOG & Co",
      start_url: "/",
      theme_color: BRAND_PRIMARY,
    });
    expect(typeof manifest.description).toBe("string");
    expect(manifest.description).not.toBe("");
  });

  it("uses the light theme's page background as the splash background", () => {
    expect(readManifest().background_color).toBe(
      themeColor("light", "background")
    );
  });

  it("lists 192 and 512 icons for any use and a maskable 512, each the size it claims", () => {
    const { icons } = readManifest();

    expect(
      icons.map((icon) => `${icon.purpose ?? "any"} ${icon.sizes}`)
    ).toEqual(["any 192x192", "any 512x512", "maskable 512x512"]);
    for (const icon of icons) {
      expect(existsSync(publicFile(icon.src)), icon.src).toBe(true);
      expect(icon.type).toBe("image/png");
      expect(pngSize(icon.src), icon.src).toBe(icon.sizes);
    }
  });
});
