/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DevMailRouteImport } from './routes/dev/mail'
import { Route as DevMailDotjsonRouteImport } from './routes/dev/mail[.]json'
import { Route as DevUiRouteImport } from './routes/dev/ui'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOpenapiSplatRouteImport } from './routes/api/openapi/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMailRoute = DevMailRouteImport.update({
  id: '/dev/mail',
  path: '/dev/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const DevMailDotjsonRoute = DevMailDotjsonRouteImport.update({
  id: '/dev/mail.json',
  path: '/dev/mail.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiSplatRoute = ApiOpenapiSplatRouteImport.update({
  id: '/api/openapi/$',
  path: '/api/openapi/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/dev/mail': typeof DevMailRoute
  '/dev/mail.json': typeof DevMailDotjsonRoute
  '/dev/ui': typeof DevUiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/openapi/$': typeof ApiOpenapiSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/dev/mail': typeof DevMailRoute
  '/dev/mail.json': typeof DevMailDotjsonRoute
  '/dev/ui': typeof DevUiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/openapi/$': typeof ApiOpenapiSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/dev/mail': typeof DevMailRoute
  '/dev/mail.json': typeof DevMailDotjsonRoute
  '/dev/ui': typeof DevUiRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/openapi/$': typeof ApiOpenapiSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/dev/mail'
    | '/dev/mail.json'
    | '/dev/ui'
    | '/api/auth/$'
    | '/api/openapi/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/dev/mail'
    | '/dev/mail.json'
    | '/dev/ui'
    | '/api/auth/$'
    | '/api/openapi/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/dev/mail'
    | '/dev/mail.json'
    | '/dev/ui'
    | '/api/auth/$'
    | '/api/openapi/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DevMailRoute: typeof DevMailRoute
  DevMailDotjsonRoute: typeof DevMailDotjsonRoute
  DevUiRoute: typeof DevUiRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOpenapiSplatRoute: typeof ApiOpenapiSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/mail': {
      id: '/dev/mail'
      path: '/dev/mail'
      fullPath: '/dev/mail'
      preLoaderRoute: typeof DevMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/mail.json': {
      id: '/dev/mail.json'
      path: '/dev/mail.json'
      fullPath: '/dev/mail.json'
      preLoaderRoute: typeof DevMailDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/$': {
      id: '/api/openapi/$'
      path: '/api/openapi/$'
      fullPath: '/api/openapi/$'
      preLoaderRoute: typeof ApiOpenapiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  DevMailRoute: DevMailRoute,
  DevMailDotjsonRoute: DevMailDotjsonRoute,
  DevUiRoute: DevUiRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOpenapiSplatRoute: ApiOpenapiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
