import { tokens } from "@smog/styles";

/**
 * Renders `@smog/styles` into the Tailwind v3 config NativeWind compiles.
 *
 * Kept as a pure string function rather than an object the config file
 * imports, for one reason: `tailwind.config.js` is loaded by the babel
 * plugin in a CommonJS context that cannot resolve a TypeScript workspace
 * import. Generating the file means the config is plain data at build time
 * and the drift test is what keeps it honest.
 *
 * Semantic roles appear twice: `surface` and `surface-dark`. NativeWind's
 * `dark:` variant needs a real class to point at, so `dark:bg-surface-dark`
 * is how a component asks for the dark role. Naming them as siblings rather
 * than nesting a `dark` palette keeps `bg-surface-dark` spellable, which a
 * nested object does not.
 */
function kebab(name: string): string {
  return name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
}

function colors(): Record<string, string> {
  const entries: Record<string, string> = {
    white: tokens.color.white,
  };

  for (const [role, value] of Object.entries(tokens.semantic.light)) {
    entries[kebab(role)] = value;
  }

  for (const [role, value] of Object.entries(tokens.semantic.dark)) {
    entries[`${kebab(role)}-dark`] = value;
  }

  for (const [step, value] of Object.entries(tokens.color.neutral)) {
    entries[`neutral-${step}`] = value;
  }

  return entries;
}

function scale(values: Record<string, number>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(values).map(([step, value]) => [step, `${value}px`])
  );
}

export function renderTailwindConfig(): string {
  const theme = {
    colors: colors(),
    spacing: scale(tokens.spacing),
    borderRadius: scale(tokens.radius),
    fontSize: scale(tokens.fontSize),
  };

  return `/**
 * GENERATED by \`bun -F @smog/ui-native generate:theme\`. Do not edit.
 *
 * The source is \`packages/styles/src/tokens.ts\`. \`src/theme.test.ts\`
 * fails if this file and that object disagree.
 */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: { extend: ${JSON.stringify(theme, null, 2)} },
};
`;
}
