/**
 * Renders `svg.gen.ts`: the artwork as raw SVG strings, still drawn in
 * `currentColor`, so the kits can render the logo inline (web: an inline
 * `<svg>`, native: `SvgXml`) and colour it with the text colour.
 *
 * Kept apart from the generator so the drift test can compare the committed
 * module with a fresh render without loading sharp.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

const HANDS = ["hand-1.svg", "hand-2.svg", "hand-3.svg"] as const;

export function renderSvgModule(artDir: string): string {
  const art = (name: string): string =>
    JSON.stringify(readFileSync(join(artDir, name), "utf8").trim());
  return [
    "// GENERATED by `bun -F @smog/brand generate` from src/art. Do not edit.",
    "// src/outputs.test.ts fails when this file and the artwork disagree.",
    "",
    "/** The horizontal SMOG & Co wordmark, in `currentColor`. */",
    `export const logoSvg = ${art("logo.svg")};`,
    "",
    "/** The stacked mark (app icon artwork), in `currentColor`. */",
    `export const logoStackedSvg = ${art("logo-stacked.svg")};`,
    "",
    "/** The illustrated hands for home and empty states, in `currentColor`. */",
    "export const handSvgs = [",
    ...HANDS.map((name) => `  ${art(name)},`),
    "] as const;",
    "",
  ].join("\n");
}
