import {
  AuthStateProvider,
  type AuthUser,
  type SessionHookResult,
  useAuthState,
} from "@smog/auth/react";
import { createWebAuthClient, type WebAuthClient } from "@smog/auth/web";
import { createI18n, type Locale } from "@smog/i18n";
import { I18nextProvider, useTranslation } from "@smog/i18n/react";
import {
  createLocalStore,
  createMemoryAdapter,
  type LocalStore,
} from "@smog/local-store";
import { LocalStoreProvider } from "@smog/local-store/react";
import { webAdapter } from "@smog/local-store/web";
import { PurgeOtherUsers, RpcProvider } from "@smog/rpc/react";
import { tokens } from "@smog/styles/tokens";
import {
  Button,
  EmptyState,
  ToastProvider,
  TooltipProvider,
} from "@smog/ui-web";
import { QueryClientProvider } from "@tanstack/react-query";
import {
  createRootRouteWithContext,
  HeadContent,
  Link,
  Outlet,
  Scripts,
  useRouter,
} from "@tanstack/react-router";
import { type ReactNode, useMemo, useState } from "react";
import { Footer } from "@/components/app-shell/footer";
import { Header } from "@/components/app-shell/header";
import { SiteConsentBanner } from "@/components/consent-banner";
import { GuestImportSheet } from "@/components/guest-import-sheet";
import { SiteAnalytics } from "@/lib/analytics";
import { AuthClientProvider } from "@/lib/auth-client";
import { LocaleProvider } from "@/lib/locale";
import { SYSTEM_THEME_SCRIPT, type Theme } from "@/lib/preferences";
import { ThemeProvider, useSystemDark } from "@/lib/theme";
import {
  getShell,
  type Shell,
  setLocale as saveLocale,
  setTheme as saveTheme,
} from "@/server/shell.functions";
import type { RouterContext } from "../router";
import stylesUrl from "../styles.css?url";

export const Route = createRootRouteWithContext<RouterContext>()({
  component: Outlet,
  head: ({ loaderData }) => ({
    // The icons are generated by `bun -F @smog/brand generate` into public/.
    links: [
      { href: stylesUrl, rel: "stylesheet" },
      { href: "/favicon.ico", rel: "icon", sizes: "48x48" },
      { href: "/icon.svg", rel: "icon", type: "image/svg+xml" },
      { href: "/apple-touch-icon.png", rel: "apple-touch-icon" },
    ],
    meta: [
      { charSet: "utf-8" },
      { content: "width=device-width, initial-scale=1", name: "viewport" },
      {
        title: createI18n(loaderData?.locale ?? "nl").t("common.appName"),
      },
    ],
  }),
  // The shell (locale, theme, session) changes only through the setters
  // below, which invalidate the router.
  loader: (): Promise<Shell> => getShell(),
  notFoundComponent: NotFound,
  shellComponent: RootDocument,
  staleTime: Number.POSITIVE_INFINITY,
});

function NotFound(): ReactNode {
  const { t } = useTranslation();
  return (
    <EmptyState
      action={
        <Button asChild>
          <Link to="/">{t("states.notFound.action")}</Link>
        </Button>
      }
      description={t("states.notFound.description")}
      illustration={1}
      level={1}
      title={t("states.notFound.title")}
    />
  );
}

/**
 * The session hook for `AuthStateProvider`: until the client has read the
 * session, the server's answer stands, so the header never flashes
 * "Sign in" for a signed-in user.
 */
function seededSessionHook(
  auth: WebAuthClient,
  initialUser: AuthUser | null
): () => SessionHookResult {
  // Only until the first answer: a later pending state (a refetch after
  // sign-out) must never bring the server's user back.
  let settled = false;
  return function useSeededSession(): SessionHookResult {
    const session = auth.useSession();
    if (!session.isPending) {
      settled = true;
    }
    if (!settled && session.isPending && !session.error) {
      return {
        data: initialUser ? { user: initialUser } : null,
        isPending: false,
        refetch: session.refetch,
      };
    }
    return session;
  };
}

/**
 * The app-wide clients, created once per document (per request on SSR).
 * The oRPC client and the QueryClient come from the router context, which
 * the loaders share (`src/router.tsx`).
 */
function useClients(shell: Shell) {
  const { api, queryClient, queryUtils } = Route.useRouteContext();
  const [clients] = useState(() => {
    const origin =
      typeof window === "undefined" ? shell.siteUrl : window.location.origin;
    const auth = createWebAuthClient(origin);
    // The server has no localStorage; hydration renders the defaults anyway.
    const store: LocalStore = createLocalStore(
      typeof window === "undefined" ? createMemoryAdapter() : webAdapter
    );
    return {
      auth,
      store,
      useSession: seededSessionHook(auth, shell.user),
    };
  });
  return { ...clients, api, queryClient, queryUtils };
}

function RootDocument({ children }: { children: ReactNode }): ReactNode {
  const shell = Route.useLoaderData();
  const clients = useClients(shell);
  const [theme, setThemeState] = useState<Theme>(shell.theme);
  const systemDark = useSystemDark();
  const dark = theme === "dark" || (theme === "system" && systemDark);
  const i18n = useMemo(() => createI18n(shell.locale), [shell.locale]);

  const themeValue = useMemo(
    () => ({
      setTheme: (next: Theme): void => {
        setThemeState(next);
        saveTheme({ data: next }).catch((error: unknown) => {
          console.error("[shell] Failed to save the theme:", error);
        });
      },
      theme,
    }),
    [theme]
  );

  return (
    <html
      className={dark ? "dark" : undefined}
      lang={shell.locale}
      // `system`: the pre-paint script may have set `dark` before hydration.
      suppressHydrationWarning
    >
      <head>
        {theme === "system" ? (
          <script
            // biome-ignore lint/security/noDangerouslySetInnerHtml: a constant pre-paint script (no user input).
            dangerouslySetInnerHTML={{ __html: SYSTEM_THEME_SCRIPT }}
          />
        ) : null}
        <ThemeColor theme={theme} />
        <HeadContent />
      </head>
      <body>
        <I18nextProvider i18n={i18n}>
          <QueryClientProvider client={clients.queryClient}>
            <RpcProvider client={clients.api} queryUtils={clients.queryUtils}>
              <AuthClientProvider client={clients.auth}>
                <AuthStateProvider useSession={clients.useSession}>
                  <PurgeOtherUsers />
                  <LocalStoreProvider store={clients.store}>
                    <SiteAnalytics>
                      <ThemeProvider value={themeValue}>
                        <SiteLocaleProvider locale={shell.locale}>
                          <TooltipProvider>
                            <ToastProvider>
                              <Layout>{children}</Layout>
                            </ToastProvider>
                          </TooltipProvider>
                        </SiteLocaleProvider>
                      </ThemeProvider>
                    </SiteAnalytics>
                  </LocalStoreProvider>
                </AuthStateProvider>
              </AuthClientProvider>
            </RpcProvider>
          </QueryClientProvider>
        </I18nextProvider>
        <Scripts />
      </body>
    </html>
  );
}

/**
 * `theme-color` (the browser chrome): the page background of the chosen
 * theme, or both, by media query, for `system`. Rendered here, not in
 * `head()`, which keeps one meta per name.
 */
function ThemeColor({ theme }: { theme: Theme }): ReactNode {
  const { dark, light } = tokens.color;
  if (theme !== "system") {
    return (
      <meta
        content={theme === "dark" ? dark.background : light.background}
        name="theme-color"
      />
    );
  }
  return (
    <>
      <meta
        content={light.background}
        media="(prefers-color-scheme: light)"
        name="theme-color"
      />
      <meta
        content={dark.background}
        media="(prefers-color-scheme: dark)"
        name="theme-color"
      />
    </>
  );
}

/**
 * The language: this browser's `locale` cookie, and signed in also the
 * account's (`user.locale`, the language of our emails) through
 * `account.updateProfile`, the one profile write path, as in the app.
 */
function SiteLocaleProvider({
  children,
  locale,
}: {
  children: ReactNode;
  locale: Locale;
}): ReactNode {
  const router = useRouter();
  const { api } = Route.useRouteContext();
  const signedIn = useAuthState().status === "signedIn";
  const value = useMemo(
    () => ({
      locale,
      setLocale: (next: Locale): void => {
        const save = async (): Promise<void> => {
          await Promise.all([
            saveLocale({ data: next }).then(() => router.invalidate()),
            signedIn ? api.account.updateProfile({ locale: next }) : null,
          ]);
        };
        save().catch((error: unknown) => {
          console.error("[shell] Failed to save the language:", error);
        });
      },
    }),
    [api, locale, router, signedIn]
  );
  return <LocaleProvider value={value}>{children}</LocaleProvider>;
}

function Layout({ children }: { children: ReactNode }): ReactNode {
  const { t } = useTranslation();
  return (
    <div className="flex min-h-screen flex-col">
      <a
        className="sr-only z-50 rounded-md bg-surface px-4 py-3 text-foreground focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:ring-2 focus:ring-focus-ring"
        href="#main"
      >
        {t("a11y.skipToContent")}
      </a>
      <noscript>
        <p className="bg-surface px-4 py-3 text-center text-foreground text-sm">
          {t("a11y.noscript")}
        </p>
      </noscript>
      <Header />
      <main className="flex flex-1 flex-col" id="main" tabIndex={-1}>
        {children}
      </main>
      <Footer />
      <GuestImportSheet />
      <SiteConsentBanner />
    </div>
  );
}
