import { boxShadow, type ElevationLevel, tokens } from "./tokens";

const ROOT_FONT_SIZE = 16;

export const GENERATED_HEADER = (source: string): string =>
  [
    `GENERATED by \`bun -F @smog/styles generate\` from ${source}. Do not edit.`,
    "The source is packages/styles/src/tokens.ts; src/generate.test.ts fails on drift.",
  ].join("\n");

/** px → rem, trimmed to at most four decimals. */
function rem(px: number): string {
  return `${Number((px / ROOT_FONT_SIZE).toFixed(4))}rem`;
}

/** `surfaceRaised` → `surface-raised`. */
export function kebab(name: string): string {
  return name.replaceAll(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

/** Tailwind v4 theme keys write a `.` in a key as `_` (`--spacing-0_5`). */
function themeKey(key: string): string {
  return key.replaceAll(".", "_");
}

function declarations(entries: [string, string][], indent = "  "): string[] {
  return entries.map(([name, value]) => `${indent}--${name}: ${value};`);
}

function colours(theme: "light" | "dark"): [string, string][] {
  return Object.entries(tokens.color[theme]).map(([role, value]) => [
    `color-${kebab(role)}`,
    value,
  ]);
}

const ELEVATION_LEVELS = Object.keys(tokens.elevation) as ElevationLevel[];

function shadows(theme: "light" | "dark"): [string, string][] {
  return ELEVATION_LEVELS.map((level) => [
    `shadow-${level}`,
    boxShadow(level, theme),
  ]);
}

function durations(): [string, string][] {
  return Object.entries(tokens.motion.duration).map(([name, ms]) => [
    `duration-${name}`,
    `${ms}ms`,
  ]);
}

function themeBlock(): string[] {
  const { fontSize, fontWeight, spacing, radius, breakpoint, layout } = tokens;
  const easing = tokens.motion.easing.standard.join(", ");
  return [
    "@theme {",
    "  --color-*: initial;",
    ...declarations(colours("light")),
    "",
    "  --spacing-*: initial;",
    ...declarations(
      Object.entries(spacing).map(([key, px]) => [
        `spacing-${themeKey(key)}`,
        rem(px),
      ])
    ),
    "",
    "  --radius-*: initial;",
    ...declarations(
      Object.entries(radius).map(([key, px]) => [
        `radius-${key}`,
        key === "full" ? `${px}px` : rem(px),
      ])
    ),
    "",
    `  --font-sans: ${tokens.fontFamily.web.join(", ")};`,
    "  --font-weight-*: initial;",
    ...declarations(
      Object.entries(fontWeight).map(([key, weight]) => [
        `font-weight-${key}`,
        String(weight),
      ])
    ),
    "  --text-*: initial;",
    ...declarations(
      Object.entries(fontSize).flatMap(([key, step]) => [
        [`text-${key}`, rem(step.size)],
        [`text-${key}--line-height`, rem(step.lineHeight)],
      ])
    ),
    "",
    "  --shadow-*: initial;",
    ...declarations(shadows("light")),
    "",
    "  --ease-*: initial;",
    `  --ease-standard: cubic-bezier(${easing});`,
    ...declarations(durations()),
    "  --default-transition-duration: var(--duration-normal);",
    "  --default-transition-timing-function: var(--ease-standard);",
    "",
    "  --breakpoint-*: initial;",
    ...declarations(
      Object.entries(breakpoint).map(([key, px]) => [
        `breakpoint-${key}`,
        rem(px),
      ])
    ),
    "",
    `  --container-content: ${rem(layout.contentMaxWidth)};`,
    `  --container-reading: ${layout.readingMaxWidthCh}ch;`,
    "}",
  ];
}

function responsiveType(): string[] {
  const lines: string[] = [];
  for (const [key, step] of Object.entries(tokens.fontSize)) {
    if ("md" in step) {
      lines.push(
        ...declarations(
          [
            [`text-${key}`, rem(step.md.size)],
            [`text-${key}--line-height`, rem(step.md.lineHeight)],
          ],
          "    "
        )
      );
    }
  }
  return [
    `@media (width >= ${rem(tokens.breakpoint.md)}) {`,
    "  :root {",
    ...lines,
    "  }",
    "}",
  ];
}

function darkBlock(): string[] {
  return [
    ".dark {",
    "  color-scheme: dark;",
    ...declarations(colours("dark")),
    ...declarations(shadows("dark")),
    "}",
  ];
}

function reducedMotion(): string[] {
  return [
    "@media (prefers-reduced-motion: reduce) {",
    "  :root {",
    ...declarations(
      durations().map(([name]) => [name, "0ms"]),
      "    "
    ),
    "  }",
    "}",
  ];
}

/**
 * Tailwind's `duration-*` utility only takes numbers, so the named
 * durations get their own utilities (they read the variables, which
 * reduced motion sets to 0).
 */
function durationUtilities(): string[] {
  return Object.keys(tokens.motion.duration).flatMap((name) => [
    `@utility duration-${name} {`,
    `  --tw-duration: var(--duration-${name});`,
    `  transition-duration: var(--duration-${name});`,
    "}",
  ]);
}

/**
 * The Tailwind v4 theme for the site and `@smog/ui-web`. Import it after
 * `tailwindcss`: `@import "@smog/styles/theme.css";`.
 */
export function renderWebThemeCss(): string {
  const header = GENERATED_HEADER("tokens.ts via src/generate-web.ts")
    .split("\n")
    .map((line) => ` * ${line}`);
  return [
    "/*",
    ...header,
    " */",
    "",
    "@custom-variant dark (&:where(.dark, .dark *));",
    "",
    ...themeBlock(),
    "",
    ":root {",
    "  color-scheme: light;",
    "}",
    "",
    ...responsiveType(),
    "",
    ...darkBlock(),
    "",
    ...reducedMotion(),
    "",
    ...durationUtilities(),
    "",
  ].join("\n");
}
