import type React from "react";
import { themeInitScript } from "@/lib/theme";

/*
 * `./styles.css` is imported by `page.tsx`, not here.
 *
 * It was imported in both places, and a layout import loads it on every route
 * in this group. That stylesheet is the Payload template's: it paints `<html>`
 * black, sets an 18px root font size, and gives every `p` a 24px margin and
 * every `h1` a 64px one. None of it sits in a cascade layer, and an unlayered
 * rule beats a layered one whatever the order — so it outranked Tailwind's
 * preflight on `/kitchen-sink` and pushed every paragraph in every card and
 * toast 24 pixels apart.
 *
 * Moving the import down a level leaves the template home page byte-identical
 * — it already imports the file itself — and takes the contamination off
 * every other route in the group. Stage 3 deletes the stylesheet with the
 * page it belongs to.
 */

export const metadata = {
  description: "A blank template using Payload in a Next.js app.",
  title: "Payload Blank Template",
};

export default async function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;

  return (
    /*
     * `suppressHydrationWarning` because the script below writes to
     * `<html class>` before React hydrates, which React would otherwise
     * report as a mismatch on every load. It suppresses the warning for this
     * element's own attributes only, not for the tree beneath it.
     */
    <html lang="en" suppressHydrationWarning>
      <head>
        {/*
         * The theme class has to be on `<html>` before the first paint, and
         * the earliest a React component can act is after hydration — one
         * painted frame too late, which a reviewer sees as a white flash on
         * every load of a page they are looking at in dark mode. A blocking
         * inline script is the only thing that runs early enough.
         */}
        <script
          // biome-ignore lint/security/noDangerouslySetInnerHtml: the content is generated by `themeInitScript()` from this repository's own constants — no request, no user and no database reaches it — and a `<script>` element takes its body no other way.
          dangerouslySetInnerHTML={{ __html: themeInitScript() }}
        />
      </head>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
